/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Drives components/muse_gadget_ble/mg_proto.c as a client would: commands,
 * settings, capture, gestures, the offline queue, the routing policy, and
 * the token proof against protocols/test-vectors/mg-token-proof-v1.json
 * (mg_proof_vectors.h, generated by the test).
 */

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mg_codec.h"
#include "mg_play.h"
#include "mg_proto.h"
#include "mg_queue.h"
#include "mg_route.h"
#include "mg_proof_vectors.h"
#include "mg_token_proof.h"
#include "mgcommands.h"

static int failures, checks;
#define CHECK(c)                                                                  \
    do {                                                                          \
        checks++;                                                                 \
        if (!(c)) {                                                               \
            fprintf(stderr, "%s:%d: CHECK failed: %s\n", __FILE__, __LINE__, #c); \
            failures++;                                                           \
        }                                                                         \
    } while (0)

/* ---- fake BLE side ------------------------------------------------------ */

typedef struct {
    mg_ch_t ch;
    size_t len;
    uint8_t d[300];
} note_t;

static note_t notes[64];
static int nnotes;
static bool notify_fails;
static int disconnects, settings_saves, mic_gain;
static bool capturing;
static uint8_t capture_codec;
static uint32_t now;

/* Throughput-test Data notifications, counted (and checked) past the note list. */
static int data_notes, data_bad;
static uint32_t data_next;
static int notify_budget = -1;   /* >= 0: notifications accepted before the "stack" is full */
static bool count_only_data;     /* the throughput test: count Data, don't keep it */

static bool f_notify(void *ctx, mg_ch_t ch, const uint8_t *d, size_t n)
{
    (void)ctx;
    if (notify_fails || notify_budget == 0) {
        return false;
    }
    if (notify_budget > 0) {
        notify_budget--;
    }
    if (ch == MG_CH_DATA && n >= 4) {
        uint32_t seq = (uint32_t)d[0] | (uint32_t)d[1] << 8 | (uint32_t)d[2] << 16 | (uint32_t)d[3] << 24;
        data_bad += seq != data_next;
        for (size_t i = 4; i < n; i++) {
            data_bad += d[i] != (uint8_t)(seq + i);
        }
        data_next = seq + 1;
        data_notes++;
        if (count_only_data) {
            return true;
        }
    }
    if (nnotes < 64 && n <= sizeof(notes[0].d)) {
        notes[nnotes].ch = ch;
        notes[nnotes].len = n;
        memcpy(notes[nnotes].d, d, n);
        nnotes++;
    }
    return true;
}
static void f_disconnect(void *ctx) { (void)ctx; disconnects++; }
static void f_capture(void *ctx, bool start, uint8_t codec)
{
    (void)ctx;
    capturing = start;
    capture_codec = codec;
}
static void f_mic_gain(void *ctx, uint8_t g) { (void)ctx; mic_gain = g; }
static void f_settings(void *ctx) { (void)ctx; settings_saves++; }
static uint32_t f_now(void *ctx) { (void)ctx; return now; }

static void clear_notes(void) { nnotes = 0; }

static void hex(const char *s, uint8_t *out, size_t *n)
{
    *n = 0;
    while (s[0] && s[1]) {
        unsigned v;
        sscanf(s, "%2x", &v);
        out[(*n)++] = (uint8_t)v;
        s += 2;
        while (*s == ' ') {
            s++;
        }
    }
}

/* Note i (negative: from the end) is on ch and equals the hex. */
static bool note_is(int i, mg_ch_t ch, const char *h)
{
    if (i < 0) {
        i += nnotes;
    }
    if (i < 0 || i >= nnotes) {
        fprintf(stderr, "  no note %d (have %d)\n", i, nnotes);
        return false;
    }
    uint8_t want[300];
    size_t n;
    hex(h, want, &n);
    bool ok = notes[i].ch == ch && notes[i].len == n && memcmp(notes[i].d, want, n) == 0;
    if (!ok) {
        fprintf(stderr, "  note %d on ch %d:", i, notes[i].ch);
        for (size_t k = 0; k < notes[i].len; k++) {
            fprintf(stderr, " %02x", notes[i].d[k]);
        }
        fprintf(stderr, "\n  want on ch %d: %s\n", ch, h);
    }
    return ok;
}

static void write_hex(mg_proto_t *p, mg_ch_t ch, const char *h)
{
    uint8_t b[300];
    size_t n;
    hex(h, b, &n);
    mg_proto_write(p, ch, b, n);
}

/* ---- RAM flash for the queue ---- */

#define FLASH_SIZE (64 * 1024)
#define SECTOR 4096
static uint8_t flash[FLASH_SIZE];
static int fail_write_after = -1;   /* bytes that land before a simulated power cut */

static bool fl_read(void *ctx, uint32_t off, void *buf, size_t n)
{
    (void)ctx;
    if (off + n > FLASH_SIZE) return false;
    memcpy(buf, flash + off, n);
    return true;
}
static bool fl_write(void *ctx, uint32_t off, const void *buf, size_t n)
{
    (void)ctx;
    if (off + n > FLASH_SIZE) return false;
    const uint8_t *b = buf;
    for (size_t i = 0; i < n; i++) {
        if (fail_write_after == 0) {
            return false;
        }
        if (fail_write_after > 0) {
            fail_write_after--;
        }
        flash[off + i] &= b[i];   /* NOR: programming only clears bits */
    }
    return true;
}
static int fl_erases;

static bool fl_erase(void *ctx, uint32_t off, size_t n)
{
    (void)ctx;
    if (off % SECTOR || n % SECTOR || off + n > FLASH_SIZE) return false;
    memset(flash + off, 0xFF, n);
    fl_erases++;
    return true;
}
static const mg_store_t store = {
    .ctx = NULL, .size = FLASH_SIZE, .sector = SECTOR, .read = fl_read, .write = fl_write, .erase = fl_erase,
};

static mg_proto_ops_t base_ops(void)
{
    return (mg_proto_ops_t){
        .notify = f_notify, .disconnect = f_disconnect, .capture = f_capture, .mic_gain = f_mic_gain,
        .settings_changed = f_settings, .now_ms = f_now,
    };
}

static int kicks;
static void f_kick(void *ctx) { (void)ctx; kicks++; }

/* The proof key Link setup left (or none), and the clear it asks for. */
static bool proof_have_key;
static uint8_t proof_k[MG_TOKEN_PROOF_KEY_LEN];
static int proof_clears;
static uint8_t next_nonce[MG_TOKEN_PROOF_NONCE_LEN];
static bool random_fails;
static bool f_proof_key(void *ctx, uint8_t k[MG_TOKEN_PROOF_KEY_LEN])
{
    (void)ctx;
    memcpy(k, proof_k, sizeof(proof_k));
    return proof_have_key;
}
static void f_proof_clear(void *ctx)
{
    (void)ctx;
    proof_clears++;
    proof_have_key = false;
}
static bool f_random(void *ctx, uint8_t *out, size_t n)
{
    (void)ctx;
    if (random_fails) {
        return false;
    }
    for (size_t i = 0; i < n; i++) {
        out[i] = next_nonce[i % sizeof(next_nonce)];
    }
    return true;
}

/* The board's speaker setting, as mg_glue keeps it: a volume and an on switch. */
static int spk_level = 70, spk_sets;
static bool spk_on = true;
static uint8_t f_spk_get(void *ctx) { (void)ctx; return spk_on ? (uint8_t)spk_level : 0; }
static void f_spk_set(void *ctx, uint8_t v)
{
    (void)ctx;
    spk_sets++;
    if (v) {
        spk_level = v;
    }
    spk_on = v != 0;
}

static int assist_last = -1, assist_calls;
static void f_assist(void *ctx, uint8_t st)
{
    (void)ctx;
    assist_last = st;
    assist_calls++;
}

/* SBC frames of a tone, as a client would stream them: 60 bytes each. */
static size_t sbc_frames(uint8_t *out, size_t cap)
{
    static mg_encoder_t e;
    CHECK(mg_encoder_open(&e, mg_data_type_audio_sbc));
    int16_t pcm[320];
    size_t n = 0;
    for (int c = 0; c < 50 && n + 300 <= cap; c++) {
        for (int i = 0; i < 320; i++) {
            pcm[i] = (int16_t)((i * 97 + c * 13) % 4000 - 2000);
        }
        n += mg_encoder_feed(&e, pcm, 320, out + n, cap - n);
    }
    return n;
}

/* ---- the routing policy ---- */

static void test_route(void)
{
    mg_route_inputs_t in = { 0 };
    in.wifi_ready = true;
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_WIFI);
    in.client_connected = in.client_ready = true;
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_WIFI);   /* push-to-talk still off */
    in.ptt_enabled = true;
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_BLE);
    CHECK(mg_route_decide(MG_POLICY_WIFI_ONLY, &in) == MG_ROUTE_WIFI);
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &in) == MG_ROUTE_BLE);
    in.client_ready = false;   /* connected but not authenticated */
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_WIFI);
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &in) == MG_ROUTE_NONE);
    in.queue_available = in.queue_enabled = true;
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &in) == MG_ROUTE_NONE);   /* a client is connected */
    in.client_connected = false;
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &in) == MG_ROUTE_QUEUE);
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_WIFI);   /* Wi-Fi up wins over the queue */
    in.wifi_ready = false;
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_QUEUE);
    in.queue_enabled = false;
    CHECK(mg_route_decide(MG_POLICY_AUTO, &in) == MG_ROUTE_WIFI);   /* the Wi-Fi path keeps its own notes */
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &in) == MG_ROUTE_NONE);
    CHECK(mg_route_decide(MG_POLICY_WIFI_ONLY, NULL) == MG_ROUTE_WIFI);

    /* A BLE-only gadget (CONFIG_MUSE_GADGET_BLE_STANDALONE): BLE_ONLY, never Wi-Fi ready. */
    mg_route_inputs_t sa = { .queue_available = true, .queue_enabled = true };
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &sa) == MG_ROUTE_QUEUE);      /* nobody connected */
    sa.client_connected = true;
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &sa) == MG_ROUTE_NONE);       /* connected, not subscribed yet */
    sa.client_ready = true;
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &sa) == MG_ROUTE_NONE);       /* push-to-talk still off */
    sa.ptt_enabled = true;
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &sa) == MG_ROUTE_BLE);
    sa = (mg_route_inputs_t){ .queue_available = false, .queue_enabled = true };
    CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &sa) == MG_ROUTE_NONE);       /* queue full or missing */
    for (int bits = 0; bits < 64; bits++) {
        mg_route_inputs_t x = { bits & 1, bits & 2, bits & 4, false, bits & 16, bits & 32 };
        CHECK(mg_route_decide(MG_POLICY_BLE_ONLY, &x) != MG_ROUTE_WIFI);
    }
}

/* ---- the queue on its own, with power cuts ---- */

static void test_queue(void)
{
    memset(flash, 0x00, sizeof(flash));   /* stale data everywhere */
    mg_queue_t q;
    CHECK(mg_queue_mount(&q, &store));
    CHECK(mg_queue_clear(&q));
    CHECK(q.count == 0 && mg_queue_used(&q) == 0 && mg_queue_capacity(&q) == FLASH_SIZE);
    uint8_t clip[5000];
    for (size_t i = 0; i < sizeof(clip); i++) {
        clip[i] = (uint8_t)(i * 7 + 3);
    }
    CHECK(mg_queue_append(&q, mg_data_type_audio_sbc, 1234, clip, 1001));
    CHECK(mg_queue_append(&q, mg_data_type_audio_lc3, 5678, clip, sizeof(clip)));   /* crosses a sector */
    CHECK(q.count == 2);

    mg_queue_t r;
    CHECK(mg_queue_mount(&r, &store));
    CHECK(r.count == 2 && r.end == q.end && !r.dirty);
    const mg_clip_t *c = mg_queue_clip(&r, 1);
    CHECK(c && c->codec == mg_data_type_audio_lc3 && c->start_ms == 5678 && c->bytes == sizeof(clip));
    uint8_t back[5000];
    CHECK(mg_queue_read(&r, 1, 0, back, sizeof(clip)) && memcmp(back, clip, sizeof(clip)) == 0);
    CHECK(mg_queue_read(&r, 0, 1000, back, 1) && back[0] == clip[1000]);
    CHECK(!mg_queue_read(&r, 0, 1000, back, 2));
    CHECK(!mg_queue_clip(&r, 2));

    /* A reset part way through a clip's data: the clip is skipped, the next one lands after it. */
    fail_write_after = 16 + 300;
    CHECK(!mg_queue_append(&r, mg_data_type_audio_sbc, 1, clip, 2000));
    fail_write_after = -1;
    mg_queue_t s;
    CHECK(mg_queue_mount(&s, &store));
    CHECK(s.count == 2 && !s.dirty);
    CHECK(mg_queue_append(&s, mg_data_type_audio_sbc, 99, clip, 700));
    CHECK(mg_queue_mount(&r, &store) && r.count == 3 && mg_queue_clip(&r, 2)->start_ms == 99);

    /* A reset inside a header: the queue refuses clips until cleared. */
    fail_write_after = 6;
    CHECK(!mg_queue_append(&r, mg_data_type_audio_sbc, 1, clip, 100));
    fail_write_after = -1;
    CHECK(mg_queue_mount(&s, &store));
    CHECK(s.count == 3 && s.dirty && !mg_queue_fits(&s, 10));

    /* Clearing erases only the first sector; old clips further on never come back. */
    CHECK(mg_queue_clear(&s));
    CHECK(mg_queue_mount(&r, &store) && r.count == 0 && !r.dirty);
    CHECK(mg_queue_append(&r, mg_data_type_audio_sbc, 7, clip, 4090));   /* into the stale second sector */
    CHECK(mg_queue_mount(&s, &store) && s.count == 1 && s.end == r.end);

    /* Fill it up. */
    int n = 0;
    while (mg_queue_append(&s, mg_data_type_audio_sbc, (uint32_t)n, clip, sizeof(clip))) {
        n++;
    }
    CHECK(n > 5 && !mg_queue_fits(&s, sizeof(clip)));
    CHECK(mg_queue_mount(&r, &store) && r.count == s.count);

    /* Prepared: the erase happens up front and the append only writes. */
    CHECK(mg_queue_clear(&s));
    CHECK(mg_queue_append(&s, mg_data_type_audio_sbc, 1, clip, 100));
    int before = fl_erases;
    CHECK(mg_queue_prepare(&s, sizeof(clip)));      /* runs into the second sector */
    CHECK(fl_erases == before + 1);
    CHECK(mg_queue_append(&s, mg_data_type_audio_sbc, 2, clip, sizeof(clip)));
    CHECK(fl_erases == before + 1);
    CHECK(mg_queue_prepare(&s, 4) && fl_erases == before + 1);   /* already erased */
    CHECK(!mg_queue_prepare(&s, FLASH_SIZE));
    CHECK(mg_queue_mount(&r, &store) && r.count == 2 && mg_queue_read(&r, 1, 0, back, sizeof(clip))
          && memcmp(back, clip, sizeof(clip)) == 0);
}

/* ---- the plain protocol ---- */

static void test_plain(void)
{
    static mg_queue_t q;
    memset(flash, 0xFF, sizeof(flash));
    CHECK(mg_queue_mount(&q, &store));
    /* A board with a vibration motor, so the buzz settings exist. */
    mg_proto_config_t cfg = { .queue = &q, .haptics = true };
    mg_proto_ops_t ops = base_ops();
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 100);
    CHECK(!mg_proto_ready(&p));
    CHECK(!mg_proto_gesture(&p, mg_gesture_button_down));
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    CHECK(mg_proto_ready(&p));
    CHECK(mg_proto_data_payload(&p) == 97);

    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");   /* request_status */
    CHECK(note_is(0, MG_CH_CONTROL, "08 01 803e 01 3c00 401f"));   /* SBC, 16 kHz, mono, 60 B, 8000 us */
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 4c 1e"));
#if MG_WITH_LC3
    CHECK(note_is(2, MG_CH_CONTROL, "10 fe 01 01 13"));
#else
    CHECK(note_is(2, MG_CH_CONTROL, "10 fe 01 01"));
#endif
    CHECK(note_is(3, MG_CH_CONTROL, "10 fe 41 00 02 03 04 05 06 07 08"));   /* every setting it accepts */
    CHECK(note_is(4, MG_CH_CONTROL, "10 fe 1e 0b"));   /* device actions: the throughput test */
    CHECK(nnotes == 5);

    /* Settings. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "41 02 01 03 01 04 2c01 05 9600 06 32 08 01");
    CHECK(nnotes == 0 && settings_saves == 1);
    CHECK(mg_proto_ptt_enabled(&p) && mg_proto_haptics(&p));
    const mg_settings_t *s = mg_proto_settings(&p);
    CHECK(s->buzz_freq_hz == 300 && s->buzz_ms == 150 && s->buzz_volume == 50 && s->queue_enabled);
    write_hex(&p, MG_CH_CONTROL, "3f 00 02 03 04 05 06 07 08");
    CHECK(note_is(-1, MG_CH_CONTROL, "3f 00 01 02 01 03 01 04 2c01 05 9600 06 32 07 01 08 01"));
    write_hex(&p, MG_CH_CONTROL, "41 02 00 55 01");   /* unknown parameter after a good one */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0100"));
    CHECK(!mg_proto_ptt_enabled(&p));
    write_hex(&p, MG_CH_CONTROL, "41 02 02");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "41 04 2c");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0200"));
    write_hex(&p, MG_CH_CONTROL, "41 00 02");   /* spec_version is read-only */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "41 07 03");   /* Opus: not a codec here */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "3f 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 3f 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "41 02 01");

    /* Mic gain and unknown commands. */
    write_hex(&p, MG_CH_CONTROL, "09 00");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 09 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "09 32");
    CHECK(mic_gain == 50);
    write_hex(&p, MG_CH_CONTROL, "33");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 33 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "4c 09");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 4c 01 0100"));

    /* Client-driven capture. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "01 03");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 01 01 0300") && !capturing);
    write_hex(&p, MG_CH_CONTROL, "01");
    CHECK(capturing && capture_codec == mg_data_type_audio_sbc);
    write_hex(&p, MG_CH_CONTROL, "02");
    CHECK(!capturing);
#if MG_WITH_LC3
    write_hex(&p, MG_CH_CONTROL, "01 13 ff");   /* trailing bytes are ignored */
    CHECK(capturing && capture_codec == mg_data_type_audio_lc3);
    CHECK(mg_proto_capture_codec(&p) == mg_data_type_audio_lc3);   /* sticks for push-to-talk */
#endif

    /* A push-to-talk utterance. */
    clear_notes();
    CHECK(mg_proto_gesture(&p, mg_gesture_button_down));
    CHECK(mg_proto_live_begin(&p, mg_proto_capture_codec(&p)));
    uint8_t frames[80] = { 0x9c };
    CHECK(mg_proto_send_data(&p, frames, 80));
    CHECK(mg_proto_gesture(&p, mg_gesture_button_up));
    mg_proto_live_end(&p, true);
    CHECK(note_is(0, MG_CH_CONTROL, "0b 00"));
#if MG_WITH_LC3
    CHECK(note_is(1, MG_CH_CONTROL, "08 13 803e 01 2800 1027"));   /* LC3, 40 B, 10000 us */
#endif
    CHECK(notes[2].ch == MG_CH_DATA && notes[2].len == 80);
    CHECK(note_is(3, MG_CH_CONTROL, "0b 01"));
    CHECK(note_is(4, MG_CH_CONTROL, "02"));
    CHECK(!mg_proto_send_data(&p, frames, 80));   /* closed */

    /* The offline queue. */
    uint8_t clip[300];
    for (int i = 0; i < 300; i++) {
        clip[i] = (uint8_t)i;
    }
    CHECK(mg_queue_append(&q, mg_data_type_audio_sbc, 42, clip, 300));
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "4c 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "4c 01 01 3c010000 00000100 0100"));   /* 316 used of 64 KiB, 1 clip */
    write_hex(&p, MG_CH_CONTROL, "4c 04 0000");
    CHECK(note_is(-1, MG_CH_CONTROL, "4c 04 0000 01 2a000000 2c010000"));
    write_hex(&p, MG_CH_CONTROL, "4c 04 0100");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 4c 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "4c 05");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 4c 01 0200"));
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "4c 05 0000");
    CHECK(note_is(0, MG_CH_CONTROL, "08 17"));
    CHECK(mg_proto_transfer_active(&p));
    notify_fails = true;   /* out of buffers: the chunk waits */
    CHECK(mg_proto_pump(&p));
    notify_fails = false;
    int chunks = 0;
    while (mg_proto_pump(&p)) {
        chunks++;
    }
    CHECK(chunks == 3);   /* 97 + 97 + 97, then the last 9 */
    CHECK(nnotes == 5 && notes[1].len == 97 && notes[4].len == 9);
    CHECK(memcmp(notes[2].d, clip + 97, 97) == 0 && memcmp(notes[4].d, clip + 291, 9) == 0);
    /* Live audio wins over a download, and a download waits for live audio. */
    write_hex(&p, MG_CH_CONTROL, "4c 05 0000");
    CHECK(mg_proto_transfer_active(&p));
    CHECK(mg_proto_live_begin(&p, mg_data_type_audio_sbc));
    CHECK(!mg_proto_transfer_active(&p));
    write_hex(&p, MG_CH_CONTROL, "4c 05 0000");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 4c 01 0400"));
    mg_proto_live_end(&p, false);
    write_hex(&p, MG_CH_CONTROL, "4c 03");
    CHECK(note_is(-1, MG_CH_CONTROL, "4c 01 01 00000000 00000100 0000"));
    CHECK(mg_proto_settings(&p)->queue_enabled);

    /* Disconnect ends a capture and forgets the connection's settings. */
    write_hex(&p, MG_CH_CONTROL, "01");
    CHECK(capturing);
    mg_proto_disconnect(&p);
    CHECK(!capturing);
    mg_proto_connect(&p);
    CHECK(!mg_proto_ptt_enabled(&p) && !mg_proto_haptics(&p) && mg_proto_capture_codec(&p) == mg_data_type_audio_sbc);
    CHECK(!mg_proto_ready(&p));

    /* Without a queue, it isn't offered. */
    mg_proto_config_t noq = { 0 };
    mg_proto_init(&p, &noq, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 1e"));
    CHECK(note_is(3, MG_CH_CONTROL, "10 fe 41 00 02 07"));   /* no queue, no motor */
    write_hex(&p, MG_CH_CONTROL, "41 08 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "41 03 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0100"));
}


/* ---- assistant_state, and a board without a vibration motor ---- */

static void test_assistant(void)
{
    /* The Waveshare C6: a display and a speaker, no vibration motor. */
    static mg_play_t pl;
    mg_play_init(&pl, 4096);
    mg_proto_config_t cfg = { .play = &pl, .assistant = true };
    mg_proto_ops_t ops = base_ops();
    ops.assistant_state = f_assist;
    ops.speaker_volume = f_spk_get;
    ops.set_speaker_volume = f_spk_set;
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 1d 83 1e"));
    CHECK(note_is(-2, MG_CH_CONTROL, "10 fe 41 00 02 07 0a"));   /* no haptics or ptt_buzz_*, speaker_volume */
    /* No motor: haptics_enabled and the buzz settings are unsupported, in get and set. */
    static const char *const nomotor[] = { "41 03 01", "41 04 d200", "41 05 6400", "41 06 50", "3f 03", "3f 04",
                                           "3f 05", "3f 06" };
    for (size_t i = 0; i < sizeof(nomotor) / sizeof(nomotor[0]); i++) {
        clear_notes();
        write_hex(&p, MG_CH_CONTROL, nomotor[i]);
        CHECK(nnotes == 1 && notes[0].d[0] == 0x19 && notes[0].d[3] == 1 && notes[0].d[4] == 0);
    }
    CHECK(!mg_proto_haptics(&p));
    /* Every listed setting is accepted by get_settings. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "3f 00 02 07 0a");
    CHECK(nnotes == 1 && notes[0].d[0] == 0x3f && notes[0].len == 9);

    /* An older client that never sends assistant_state: the face ends the turn itself after playback. */
    CHECK(!p.reports_state);

    /* assistant_state: each defined state reaches the board, with no reply. */
    static const uint8_t states[] = { 2, 3, 4, 5, 0 };
    for (size_t i = 0; i < sizeof(states); i++) {
        clear_notes();
        uint8_t m[2] = { 0x83, states[i] };
        mg_proto_write(&p, MG_CH_CONTROL, m, 2);
        CHECK(nnotes == 0 && assist_last == states[i]);
    }
    int calls = assist_calls;
    write_hex(&p, MG_CH_CONTROL, "83 01");   /* 1 is reserved */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 83 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "83 06");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 83 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "83");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 83 01 0200"));
    CHECK(assist_calls == calls);
    write_hex(&p, MG_CH_CONTROL, "83 02 ff");   /* trailing bytes are ignored */
    CHECK(assist_last == 2);
    CHECK(p.reports_state);
    /* A client that goes away leaves the device idle, and the next one starts as an older client. */
    mg_proto_disconnect(&p);
    CHECK(assist_last == 0);
    CHECK(!p.reports_state);
    calls = assist_calls;
    mg_proto_disconnect(&p);   /* not connected: nothing more */
    CHECK(assist_calls == calls);

    /* A board without a display or light doesn't offer it. */
    mg_proto_config_t none = { 0 };
    ops.assistant_state = NULL;
    mg_proto_init(&p, &none, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "83 02");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 83 01 0100"));
    calls = assist_calls;
    mg_proto_disconnect(&p);
    CHECK(assist_calls == calls);
    mg_play_release(&pl);
}

/* ---- the client's state for the screen (mg_proto_link) ---- */

static const note_t *tp_report_note(void)
{
    for (int i = nnotes - 1; i >= 0; i--) {
        if (notes[i].ch == MG_CH_CONTROL && notes[i].len == 19 && notes[i].d[0] == mg_command_device_action) {
            return &notes[i];
        }
    }
    return NULL;
}

static uint32_t le32(const uint8_t *b)
{
    return (uint32_t)b[0] | (uint32_t)b[1] << 8 | (uint32_t)b[2] << 16 | (uint32_t)b[3] << 24;
}

/* device_action throughput_test (mgcommands.h, Throughput test). */
static void test_throughput(void)
{
    mg_proto_config_t cfg = { 0 };
    mg_proto_ops_t ops = base_ops();
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 247);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    clear_notes();

    /* Listed, with its typed list of actions. */
    write_hex(&p, MG_CH_CONTROL, "0a");
    bool listed = false, typed = false;
    for (int i = 0; i < nnotes; i++) {
        if (notes[i].d[0] == mg_command_supported_features && notes[i].d[1] != mg_command_sub_feature) {
            listed = memchr(&notes[i].d[1], mg_command_device_action, notes[i].len - 1) != NULL;
        }
        typed |= note_is(i, MG_CH_CONTROL, "10 fe 1e 0b");
    }
    CHECK(listed && typed);

    /* Packet format and counting, shared with the bench client. */
    uint8_t pkt[244], r[19];
    mg_tp_count_t c = { 0 };
    mg_tp_fill(pkt, sizeof(pkt), 7);
    CHECK(le32(pkt) == 7 && pkt[4] == 11 && pkt[243] == (uint8_t)(7 + 243));
    for (uint32_t s = 0; s < 6; s++) {
        if (s != 3) {
            mg_tp_fill(pkt, sizeof(pkt), s);
            CHECK(mg_tp_account(&c, pkt, sizeof(pkt), 100 + s * 10));
        }
    }
    CHECK(!mg_tp_account(&c, pkt, 2, 200));
    CHECK(mg_tp_report(&c, r) == 19 && le32(&r[3]) == 5 * 244 && le32(&r[7]) == 5 && le32(&r[11]) == 50 &&
          le32(&r[15]) == 1);

    /* Send for 1 s: change_data_type, then as many MTU-3 packets as the stack takes. */
    clear_notes();
    now = 1000;
    data_notes = data_bad = 0;
    data_next = 0;
    count_only_data = true;
    write_hex(&p, MG_CH_CONTROL, "1e 0b 01 0100");
    CHECK(note_is(0, MG_CH_CONTROL, "08 14"));
    CHECK(mg_proto_transfer_active(&p));
    write_hex(&p, MG_CH_CONTROL, "1e 0b 02 0000");   /* busy: one at a time */
    CHECK(note_is(1, MG_CH_CONTROL, "19 1e 01 0400"));
    write_hex(&p, MG_CH_CONTROL, "01");               /* start_mic: busy too */
    CHECK(note_is(2, MG_CH_CONTROL, "19 01 01 0400"));
    for (int tick = 0; tick < 300 && mg_proto_transfer_active(&p); tick++) {
        notify_budget = 4;    /* the stack takes four per round, like a connection event */
        mg_proto_pump(&p);
        now += 5;
    }
    notify_budget = -1;
    count_only_data = false;
    CHECK(!mg_proto_transfer_active(&p));
    const note_t *rep = tp_report_note();
    CHECK(rep && le32(&rep->d[7]) == (uint32_t)data_notes && le32(&rep->d[3]) == (uint32_t)data_notes * 244);
    CHECK(data_notes >= 790 && data_notes <= 804 && data_bad == 0 && le32(&rep->d[15]) == 0);
    CHECK(le32(&rep->d[11]) >= 990 && le32(&rep->d[11]) <= 1000);

    /* Receive: change_data_type from the client, then Data writes; stop reports. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1e 0b 02 0000");
    CHECK(nnotes == 0);
    mg_tp_fill(pkt, sizeof(pkt), 50);
    mg_proto_write(&p, MG_CH_DATA, pkt, sizeof(pkt));     /* before change_data_type: not counted */
    write_hex(&p, MG_CH_CONTROL, "08 14");
    CHECK(nnotes == 0);
    for (uint32_t s = 0; s < 20; s++) {
        if (s == 9 || s == 10) {
            continue;
        }
        mg_tp_fill(pkt, sizeof(pkt), s);
        mg_proto_write(&p, MG_CH_DATA, pkt, sizeof(pkt));
        now += 3;
    }
    write_hex(&p, MG_CH_CONTROL, "1e 0b 00");
    rep = tp_report_note();
    CHECK(rep && le32(&rep->d[3]) == 18 * 244 && le32(&rep->d[7]) == 18 && le32(&rep->d[15]) == 2);

    /* Receive with a duration reports from the tick; then Data is ignored. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1e 0b 02 0100");
    write_hex(&p, MG_CH_CONTROL, "08 14");
    mg_proto_write(&p, MG_CH_DATA, pkt, sizeof(pkt));
    mg_proto_tick(&p);
    CHECK(!tp_report_note());
    now += 1000;
    mg_proto_tick(&p);
    rep = tp_report_note();
    CHECK(rep && le32(&rep->d[7]) == 1);

    /* Refusals: wrong direction, unknown action, client change_data_type outside a test. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1e 0b 07");
    CHECK(note_is(0, MG_CH_CONTROL, "19 1e 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "1e 00");
    CHECK(note_is(1, MG_CH_CONTROL, "19 1e 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "08 14");
    CHECK(note_is(2, MG_CH_CONTROL, "19 08 01 0100"));
    /* A disconnect ends a test without a report. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1e 0b 01 0000");
    mg_proto_disconnect(&p);
    CHECK(!mg_proto_transfer_active(&p));
}

static void test_link(void)
{
    mg_proto_config_t cfg = { 0 };
    mg_proto_ops_t ops = base_ops();
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    /* Nobody yet, and not set up: "open the app". Set up (device tokens): disconnected. */
    CHECK(mg_proto_link(&p, false) == MG_LINK_NEVER);
    CHECK(mg_proto_link(&p, true) == MG_LINK_DISCONNECTED);
    CHECK(strcmp(mg_link_name(MG_LINK_READY), "ready") == 0);

    /* Connected: connecting until Control and Data are both subscribed. */
    mg_proto_connect(&p);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    CHECK(mg_proto_link(&p, false) == MG_LINK_SESSION);   /* push-to-talk off */
    write_hex(&p, MG_CH_CONTROL, "41 02 01");
    CHECK(mg_proto_link(&p, false) == MG_LINK_READY);
    write_hex(&p, MG_CH_CONTROL, "41 02 00");
    CHECK(mg_proto_link(&p, false) == MG_LINK_SESSION);
    write_hex(&p, MG_CH_CONTROL, "41 02 01");

    /* The app unsubscribes (CCCD 0) while the link stays up: not ready. */
    mg_proto_subscribe(&p, MG_CH_DATA, false);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING && !mg_proto_ready(&p));
    mg_proto_subscribe(&p, MG_CH_CONTROL, false);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING);
    /* Subscribing again on the same connection: push-to-talk is per connection, so it's kept. */
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    CHECK(mg_proto_link(&p, false) == MG_LINK_READY);

    /* Disconnected, for any reason (the central, a supervision timeout, Bluetooth off on the
     * phone, the app killed): NimBLE reports each as one disconnect. Never "open the app" again. */
    mg_proto_disconnect(&p);
    CHECK(mg_proto_link(&p, false) == MG_LINK_DISCONNECTED && !mg_proto_ptt_enabled(&p));
    mg_proto_disconnect(&p);   /* twice (a stray event) is harmless */
    CHECK(mg_proto_link(&p, false) == MG_LINK_DISCONNECTED);

    /* A reconnection that never subscribes stays connecting; subscriptions and push-to-talk
     * didn't carry over from the last connection. */
    mg_proto_connect(&p);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING);
    CHECK(!mg_proto_ready(&p) && !mg_proto_ptt_enabled(&p));
    write_hex(&p, MG_CH_CONTROL, "41 02 01");   /* a write without notifications on: still not ready */
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    CHECK(mg_proto_link(&p, false) == MG_LINK_READY);   /* push-to-talk was set on this connection */
    /* A new connection replacing one that never reported its end (no disconnect event): reset. */
    mg_proto_connect(&p);
    CHECK(mg_proto_link(&p, false) == MG_LINK_CONNECTING && !mg_proto_ptt_enabled(&p));
    mg_proto_disconnect(&p);
}

/* ---- token proof ---- */

static void unhex(const char *h, uint8_t *out, size_t want)
{
    size_t n = 0;
    hex(h, out, &n);
    CHECK(n == want);
}

static void proof_write(mg_proto_t *p, uint8_t sub, const uint8_t *b, size_t n)
{
    uint8_t m[2 + 64] = { mg_command_token_proof, sub };
    memcpy(m + 2, b, n);
    mg_proto_write(p, MG_CH_CONTROL, m, 2 + n);
}

static void test_proof(void)
{
    mg_proto_config_t cfg = { 0 };
    mg_proto_ops_t ops = base_ops();
    ops.random = f_random;
    ops.proof_key = f_proof_key;
    ops.proof_clear = f_proof_clear;
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 100);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);

    /* Listed between the commands it accepts. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 22 1e"));

    /* Every vector: K from the token as provisioned, then a whole exchange. */
    uint8_t cn[16], dn[16], k[32], dmac[32], cmac[32], got[32];
    for (size_t v = 0; v < sizeof(PROOF_VECTORS) / sizeof(PROOF_VECTORS[0]); v++) {
        unhex(PROOF_VECTORS[v].cn, cn, 16);
        unhex(PROOF_VECTORS[v].dn, dn, 16);
        unhex(PROOF_VECTORS[v].k, k, 32);
        unhex(PROOF_VECTORS[v].dmac, dmac, 32);
        unhex(PROOF_VECTORS[v].cmac, cmac, 32);
        CHECK(mg_token_proof_key(PROOF_VECTORS[v].access, PROOF_VECTORS[v].node, got) && !memcmp(got, k, 32));
        CHECK(mg_token_proof_mac(k, true, cn, dn, got) && !memcmp(got, dmac, 32));
        CHECK(mg_token_proof_mac(k, false, cn, dn, got) && !memcmp(got, cmac, 32));
        memcpy(proof_k, k, 32);
        proof_have_key = true;
        memcpy(next_nonce, dn, 16);
        clear_notes();
        write_hex(&p, MG_CH_CONTROL, PROOF_VECTORS[v].challenge);
        CHECK(note_is(-1, MG_CH_CONTROL, PROOF_VECTORS[v].response) && nnotes == 1);
        CHECK(!mg_proto_proof_matched(&p));
        write_hex(&p, MG_CH_CONTROL, PROOF_VECTORS[v].confirm);
        CHECK(note_is(-1, MG_CH_CONTROL, "22 03 01") && mg_proto_proof_matched(&p));
        /* The match lasts for the connection; another confirm needs another challenge. */
        write_hex(&p, MG_CH_CONTROL, PROOF_VECTORS[v].confirm);
        CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0300") && mg_proto_proof_matched(&p));
        /* clear: result 1 first, then the board resets setup. */
        int before = proof_clears;
        write_hex(&p, MG_CH_CONTROL, "22 04");
        CHECK(note_is(-1, MG_CH_CONTROL, "22 03 01") && proof_clears == before + 1);
        CHECK(!mg_proto_proof_matched(&p));
        write_hex(&p, MG_CH_CONTROL, "22 04");   /* not twice */
        CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0600") && proof_clears == before + 1);
    }

    /* No key (not set up): not_found, nothing pending. */
    proof_have_key = false;
    write_hex(&p, MG_CH_CONTROL, "22 00 000102030405060708090a0b0c0d0e0f");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0500"));
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0300"));

    /* A wrong confirm: result 0, and clear stays refused. */
    unhex(PROOF_VECTORS[0].k, proof_k, 32);
    unhex(PROOF_VECTORS[0].dn, next_nonce, 16);
    unhex(PROOF_VECTORS[0].cn, cn, 16);
    unhex(PROOF_VECTORS[0].cmac, cmac, 32);
    proof_have_key = true;
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    uint8_t bad[32];
    memcpy(bad, cmac, 32);
    bad[31] ^= 1;
    proof_write(&p, mg_token_proof_confirm, bad, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "22 03 00") && !mg_proto_proof_matched(&p));
    write_hex(&p, MG_CH_CONTROL, "22 04");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0600") && proof_clears == (int)(sizeof(PROOF_VECTORS) / sizeof(PROOF_VECTORS[0])));

    /* A new challenge restarts: a confirm for the first one no longer matches. */
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    next_nonce[0] ^= 0xff;
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "22 03 00"));
    unhex(PROOF_VECTORS[0].dn, next_nonce, 16);

    /* Lengths: a short challenge, a short confirm (the challenge stays pending), trailing bytes. */
    write_hex(&p, MG_CH_CONTROL, "22 00 0102");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0200"));
    write_hex(&p, MG_CH_CONTROL, "22");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0200"));
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, PROOF_VECTORS[0].challenge);
    write_hex(&p, MG_CH_CONTROL, "22 02 0102");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0200"));
    uint8_t longer[33];
    memcpy(longer, cmac, 32);
    longer[32] = 0xee;
    proof_write(&p, mg_token_proof_confirm, longer, 33);
    CHECK(note_is(-1, MG_CH_CONTROL, "22 03 01"));
    uint8_t longcn[17];
    memcpy(longcn, cn, 16);
    longcn[16] = 0xee;
    clear_notes();
    proof_write(&p, mg_token_proof_challenge, longcn, 17);
    CHECK(note_is(-1, MG_CH_CONTROL, PROOF_VECTORS[0].response));

    /* Only the client's sub-commands are taken. */
    write_hex(&p, MG_CH_CONTROL, "22 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "22 03 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "22 05");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0100"));

    /* Nothing is gated on it: settings work without a proof. */
    write_hex(&p, MG_CH_CONTROL, "3f 00");
    CHECK(note_is(-1, MG_CH_CONTROL, "3f 00 01"));

    /* A disconnect forgets the match and anything pending. */
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(mg_proto_proof_matched(&p));
    mg_proto_disconnect(&p);
    CHECK(!mg_proto_proof_matched(&p));
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 100);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    write_hex(&p, MG_CH_CONTROL, "22 04");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0600"));
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    mg_proto_connect(&p);   /* a new connection without a disconnect event */
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0300"));

    /* No random bytes: busy, nothing pending. A response that couldn't go: nothing pending. */
    mg_proto_set_mtu(&p, 100);
    random_fails = true;
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0400"));
    random_fails = false;
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0300"));
    notify_fails = true;
    proof_write(&p, mg_token_proof_challenge, cn, 16);
    notify_fails = false;
    proof_write(&p, mg_token_proof_confirm, cmac, 32);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0300"));

    /* The secrets go with the connection. */
    mg_proto_disconnect(&p);
    static const uint8_t zero[sizeof(p.proof)];
    CHECK(memcmp(&p.proof, zero, sizeof(zero)) == 0);

    /* A board without the ops doesn't offer it. */
    ops = base_ops();
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 100);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    write_hex(&p, MG_CH_CONTROL, PROOF_VECTORS[0].challenge);
    CHECK(note_is(-1, MG_CH_CONTROL, "19 22 01 0100"));
    mg_proto_disconnect(&p);

    /* The constant-time compare. */
    CHECK(mg_token_proof_equal(cmac, cmac, 32) && !mg_token_proof_equal(cmac, bad, 32));
}

static void test_stream(void)
{
    static mg_play_t pl;
    mg_play_init(&pl, 4096);
    mg_proto_config_t cfg = { .play = &pl };
    mg_proto_ops_t ops = base_ops();
    ops.play_kick = f_kick;
    ops.speaker_volume = f_spk_get;
    ops.set_speaker_volume = f_spk_set;
    static mg_proto_t p;
    mg_proto_init(&p, &cfg, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_set_mtu(&p, 247);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    mg_proto_subscribe(&p, MG_CH_DATA, true);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 1d 1e"));

    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1d 00");
#if MG_WITH_LC3
    CHECK(note_is(0, MG_CH_CONTROL, "1d 01 05  01 03 01 13 06  02 00100000  03 05 803e0000 401f0000 007d0000 44ac0000 80bb0000  04 0001  05 01"));
#else
    CHECK(note_is(0, MG_CH_CONTROL, "1d 01 05  01 02 01 06  02 00100000  03 05 803e0000 401f0000 007d0000 44ac0000 80bb0000  04 0001  05 01"));
#endif
    /* Bad start_streaming requests. */
    write_hex(&p, MG_CH_CONTROL, "1d 02");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0200"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 09 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 03");   /* Opus */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 00");          /* no codec */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 02 01 01 04 02");   /* stereo */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 02 01 01 02 80bb");  /* rate cut short */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0200"));
    write_hex(&p, MG_CH_CONTROL, "1d 02 02 01 01 02 22560000");   /* 22050 Hz */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0300"));
    write_hex(&p, MG_CH_CONTROL, "1d 09");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "1d 03 05");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0300"));
    CHECK(!mg_play_active(&pl) && kicks == 0);
    /* Data before start_streaming is ignored. */
    static uint8_t sbc[16384];
    size_t n = sbc_frames(sbc, sizeof(sbc));
    CHECK(n >= 3000 && n % 60 == 0);
    mg_proto_write(&p, MG_CH_DATA, sbc, 180);
    CHECK(pl.st.bytes_received == 0);

    /* Start: buffer_update, then Data fills the buffer. */
    now = 1000;
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1d 02 03 01 01 02 803e0000 04 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 05 00100000 00000000") && kicks == 1 && mg_play_active(&pl));
    for (int i = 0; i < 4; i++) {
        mg_proto_write(&p, MG_CH_DATA, sbc + 180 * i, 180);
    }
    write_hex(&p, MG_CH_CONTROL, "1d 04");
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 05 300d0000 d0020000"));   /* 4096 - 720 = 3376, 720 */
    /* Periodic updates: after 250 ms, or 100 ms if the space changed. */
    clear_notes();
    now += 50;
    mg_proto_stream_tick(&p);
    CHECK(nnotes == 0);
    now += 60;
    mg_proto_stream_tick(&p);
    CHECK(nnotes == 0);   /* unchanged */
    mg_proto_write(&p, MG_CH_DATA, sbc + 720, 60);
    mg_proto_stream_tick(&p);
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 05 f40c0000 0c030000"));
    now += 260;
    mg_proto_stream_tick(&p);
    CHECK(nnotes == 2);
    /* stop keep: nothing yet; the playback task plays out the buffer, then stop_streaming keep. */
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1d 03 00");
    CHECK(nnotes == 0 && pl.state == MG_PLAY_DRAINING && kicks == 2);
    uint8_t buf[MG_PLAY_MAX_POP];
    size_t popped = 0, got;
    while ((got = mg_play_pop(&pl, buf, sizeof(buf), 20000)) != 0) {
        popped += got;
    }
    CHECK(popped == 780 && pl.state == MG_PLAY_DONE);
    mg_proto_stream_tick(&p);
    CHECK(nnotes == 0);   /* no updates once stopping */
    mg_proto_stream_finished(&p);
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 03 00") && !mg_play_active(&pl) && pl.buf == NULL);
    /* stop with nothing playing: echoed. */
    write_hex(&p, MG_CH_CONTROL, "1d 03 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 03 01"));
    /* stop drop: at once. */
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 01");
    mg_proto_write(&p, MG_CH_DATA, sbc, 600);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1d 03 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 03 01") && nnotes == 1 && pl.state == MG_PLAY_IDLE);
    /* stop keep with an empty buffer: done at once too. */
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 01");
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "1d 03 00");
    CHECK(nnotes == 0 && pl.state == MG_PLAY_DONE);
    mg_proto_stream_finished(&p);
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 03 00"));
    /* Push-to-talk takes the audio path: stop_streaming drop, and start is busy until it's done. */
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 01");
    clear_notes();
    mg_proto_claim_audio(&p, true);
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 03 01") && pl.state == MG_PLAY_IDLE);
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 01");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0400") && !mg_play_active(&pl));
    mg_proto_claim_audio(&p, false);
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 06");   /* PCM, 16 kHz */
    CHECK(note_is(-1, MG_CH_CONTROL, "1d 05 00100000 00000000"));
    uint8_t pcm[244] = { 0 };
    mg_proto_write(&p, MG_CH_DATA, pcm, 244);
    mg_proto_write(&p, MG_CH_DATA, pcm, 3);   /* odd: not whole samples */
    CHECK(pl.st.bytes_received == 247 && pl.st.bad_frames == 1);
    /* A client capture can run beside playback (the loopback test does). */
    write_hex(&p, MG_CH_CONTROL, "01");
    CHECK(capturing && mg_play_active(&pl));
    write_hex(&p, MG_CH_CONTROL, "02");
    /* Disconnect ends it, with nobody to tell. */
    clear_notes();
    mg_proto_disconnect(&p);
    CHECK(!mg_play_active(&pl) && nnotes == 0);
    mg_play_release(&pl);
    CHECK(pl.buf == NULL);

    /* speaker_volume: the board's speaker setting, 0 = off, persisted by the board. */
    mg_proto_connect(&p);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    clear_notes();
    int saves = settings_saves;
    write_hex(&p, MG_CH_CONTROL, "3f 0a 00");
    CHECK(note_is(-1, MG_CH_CONTROL, "3f 0a 46 00 01"));   /* 70, spec_version 1 */
    write_hex(&p, MG_CH_CONTROL, "41 0a 00");
    CHECK(!spk_on && spk_level == 70 && nnotes == 1);      /* off; the level is kept; no reply */
    write_hex(&p, MG_CH_CONTROL, "3f 0a");
    CHECK(note_is(-1, MG_CH_CONTROL, "3f 0a 00"));
    write_hex(&p, MG_CH_CONTROL, "41 0a 3c");
    CHECK(spk_on && spk_level == 60);
    write_hex(&p, MG_CH_CONTROL, "3f 0a");
    CHECK(note_is(-1, MG_CH_CONTROL, "3f 0a 3c"));
    write_hex(&p, MG_CH_CONTROL, "41 0a 65");               /* 101 */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0300") && spk_level == 60);
    write_hex(&p, MG_CH_CONTROL, "41 0a");                  /* no value */
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0200"));
    CHECK(settings_saves == saves && spk_sets == 2);        /* the board persists it, not mg's settings */
    /* Playback with the speaker off is still accepted (and paced; silent on the board). */
    write_hex(&p, MG_CH_CONTROL, "41 0a 00");
    write_hex(&p, MG_CH_CONTROL, "1d 02 01 01 01");
    CHECK(mg_play_active(&pl));
    write_hex(&p, MG_CH_CONTROL, "1d 03 01");
    write_hex(&p, MG_CH_CONTROL, "41 0a 46");
    mg_proto_disconnect(&p);
    mg_play_release(&pl);

    /* Without a speaker, stream_audio and speaker_volume aren't offered. */
    mg_proto_config_t none = { 0 };
    ops.speaker_volume = NULL;
    ops.set_speaker_volume = NULL;
    mg_proto_init(&p, &none, &ops, NULL);
    mg_proto_connect(&p);
    mg_proto_subscribe(&p, MG_CH_CONTROL, true);
    clear_notes();
    write_hex(&p, MG_CH_CONTROL, "0a");
    CHECK(note_is(1, MG_CH_CONTROL, "10 01 02 09 0a 3f 41 1e"));
    write_hex(&p, MG_CH_CONTROL, "1d 00");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 1d 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "3f 0a");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 3f 01 0100"));
    write_hex(&p, MG_CH_CONTROL, "41 0a 3c");
    CHECK(note_is(-1, MG_CH_CONTROL, "19 41 01 0100") && spk_level == 70);
}

int main(void)
{
    test_route();
    test_queue();
    test_plain();
    test_stream();
    test_assistant();
    test_proof();
    test_link();
    test_throughput();
    if (failures) {
        fprintf(stderr, "FAIL: %d checks\n", failures);
        return 1;
    }
    printf("PASS mg_proto (%d checks)\n", checks);
    return 0;
}
