#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Turns the Link pairing v5 and token proof vectors into one C header.

  gen_vectors.py LINK_PAIRING_V5_JSON MG_TOKEN_PROOF_JSON OUT_H

Only the community vectors of link_pairing_v5.json are used: the gadget
never signs (no manufacturer attestation).
"""

import base64
import json
import sys


def b64u(s):
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def arr(b):
    return "{" + ", ".join("0x%02x" % x for x in b) + "}"


def cstr(s):
    out = []
    for ch in s.encode("utf-8"):
        if ch in (0x22, 0x5C):
            out.append("\\" + chr(ch))
        elif ch == 0x0A:
            out.append("\\n")
        elif 0x20 <= ch < 0x7F:
            out.append(chr(ch))
        else:
            out.append("\\x%02x\"\"" % ch)
    return '"' + "".join(out) + '"'


def main():
    link_path, proof_path, out = sys.argv[1:4]
    link = json.load(open(link_path))
    proof = json.load(open(proof_path))
    L = ["/* Generated by gen_vectors.py. Do not edit. */\n", "#include <stdint.h>\n\n"]

    L.append("struct link_vec {\n  const char *name, *policy, *device_id, *node_id, *mac, *fw;\n"
             "  uint8_t mobile_priv[32], device_priv[32];\n"
             "  const char *mobile_pub, *device_pub, *mobile_nonce, *device_nonce;\n"
             "  uint8_t ecdh[32]; const char *transcript, *transcript_hash;\n"
             "  uint8_t session_secret[32], mobile_tx_key[32], mobile_rx_key[32];\n"
             "  const char *session_id, *cf_plain, *cf_aad, *cf_ct, *cf_tag;\n};\n")
    L.append("static const struct link_vec link_vecs[] = {\n")
    n = 0
    for v in link["vectors"]:
        if not v["community"]:
            continue
        n += 1
        L.append("  {%s, %s, %s, %s, %s, %s,\n" % tuple(cstr(v[k]) for k in (
            "name", "pairing_policy", "device_id", "node_id", "mac", "firmware_version")))
        L.append("   %s,\n   %s,\n" % (arr(bytes.fromhex(v["mobile_private_scalar_hex"])),
                                      arr(bytes.fromhex(v["device_private_scalar_hex"]))))
        L.append("   %s, %s, %s, %s,\n" % tuple(cstr(v[k]) for k in (
            "mobile_pub", "device_pub", "mobile_nonce", "device_nonce")))
        L.append("   %s, %s, %s,\n" % (arr(bytes.fromhex(v["ecdh_secret_hex"])), cstr(v["transcript"]),
                                       cstr(v["transcript_hash"])))
        L.append("   %s, %s, %s,\n" % tuple(arr(bytes.fromhex(v[k])) for k in (
            "session_secret_hex", "mobile_tx_key_hex", "mobile_rx_key_hex")))
        L.append("   %s, %s, %s, %s, %s},\n" % tuple(cstr(v[k]) for k in (
            "session_id", "client_finished_plaintext", "client_finished_aad",
            "client_finished_ciphertext", "client_finished_tag")))
    L.append("};\n#define LINK_VEC_COUNT %d\n\n" % n)

    L.append("#define PROOF_SALT %s\n#define PROOF_DEVICE_LABEL %s\n#define PROOF_CLIENT_LABEL %s\n" % (
        cstr(proof["salt"]), cstr(proof["device_label"]), cstr(proof["client_label"])))
    L.append("struct proof_frame { const uint8_t *b; uint16_t n; };\n")
    L.append("struct proof_vec {\n  const char *name, *access_token, *node_id;\n"
             "  uint8_t client_nonce[16], device_nonce[16], K[32], device_mac[32], client_mac[32];\n"
             "  struct proof_frame challenge, response, confirm, result, clear;\n};\n")
    frames = []
    for i, v in enumerate(proof["vectors"]):
        for k in ("challenge", "response", "confirm", "result", "clear"):
            b = bytes.fromhex(v["frames"][k])
            frames.append("static const uint8_t pf_%d_%s[] = %s;\n" % (i, k, arr(b)))
    L.extend(frames)
    L.append("static const struct proof_vec proof_vecs[] = {\n")
    for i, v in enumerate(proof["vectors"]):
        L.append("  {%s, %s, %s,\n" % (cstr(v["name"]), cstr(v["access_token"]), cstr(v["node_id"])))
        L.append("   %s,\n" % ", ".join(arr(bytes.fromhex(v[k])) for k in (
            "client_nonce", "device_nonce", "K", "device_mac", "client_mac")))
        L.append("   %s},\n" % ", ".join("{pf_%d_%s, sizeof(pf_%d_%s)}" % (i, k, i, k) for k in (
            "challenge", "response", "confirm", "result", "clear")))
    L.append("};\n#define PROOF_VEC_COUNT %d\n" % len(proof["vectors"]))
    open(out, "w").write("".join(L))


if __name__ == "__main__":
    main()
